# Generated by Django 3.2.7 on 2021-09-12 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210912_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 17, 28, 58, 637129, tzinfo=utc)),
        ),
    ]
