# Generated by Django 3.2.7 on 2021-09-12 17:33

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0006_remove_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(blank=True,
                                       default=datetime.datetime(2021, 9, 12, 17, 33, 57, 381897, tzinfo=utc),
                                       null=True),
        ),
    ]
